version: "3.7"
services:
  test:
    image: "myapp:latest"
    build: ./
    container_name: "test"
    ports:
      - '8080:8080'
    environment:
      CUSTOM_IS-TEST: true
  release:
    image: "myapp:latest"
    build: ./
    container_name: "release"
    ports:
      - '8081:8080'
    environment:
      CUSTOM_IS-TEST: false
